// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PickFood: typeof import('./src/components/PickFood.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TopHead: typeof import('./src/components/TopHead.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarRadio: typeof import('@varlet/ui')['_RadioComponent']
    VarRadioGroup: typeof import('@varlet/ui')['_RadioGroupComponent']
    VarRate: typeof import('@varlet/ui')['_RateComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarUploader: typeof import('@varlet/ui')['_UploaderComponent']
  }
}

export { }
